# Based on https://github.com/bitnami/bitnami-docker-moodle

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    platform: linux/x86_64
    restart: unless-stopped
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - './persist/mariadb:/bitnami/mariadb'
  moodle:
    build: .
    platform: linux/x86_64
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './persist/moodle:/bitnami/moodle'
      - './persist/moodledata:/bitnami/moodledata'
    depends_on:
      - mariadb
